require "ifj21"

function main()
    local a : integer = 10

    if 9 then
        if (10) then
            write(a, "\n")
            local a : integer = a + 200
            write   (a, "\n")
            if nil ~= nil  then
            else
                write(a, "\n")
                local a : number = 98.80
                write(a, "\n")
            end
        else end
        write(a, "\n")
    else end

    write(a, "\n")
end

main()
