/*
 * This file was generated by build_grammar.py, DO NOT MODIFY!
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#include "type.h"
#include "dynstring.h"

// order of these two enums is crucial
typedef enum
{
    NT_PROGRAM,
    NT_TYPE_LIST,
    NT_COND_STATEMENT,
    NT_RET_EXPRESSION_LIST,
    NT_OPTIONAL_FOR_STEP,
    NT_REPEAT_UNTIL,
    NT_OPT_BINOP,
    NT_GLOBAL_STATEMENT,
    NT_IDENTIFIER_LIST_WITH_TYPES,
    NT_GLOBAL_STATEMENT_LIST,
    NT_EXPRESSION_LIST,
    NT_STATEMENT,
    NT_FOR_LOOP,
    NT_FUNC_DECL,
    NT_FUNC_TYPE_LIST2,
    NT_STATEMENT_LIST2,
    NT_EXPRESSION_LIST2,
    NT_FUNC_TYPE_LIST,
    NT_DECLARATION,
    NT_RET_EXPRESSION_LIST2,
    NT_IDENTIFIER_LIST,
    NT_FUNC_DEF,
    NT_IDENTIFIER_LIST2,
    NT_UNOP,
    NT_ASSIGNMENT,
    NT_IDENTIFIER_WITH_TYPE,
    NT_PAREN_EXP_LIST_OR_ID_LIST2,
    NT_OPTIONAL_FUN_EXPRESSION_LIST,
    NT_BINOP,
    NT_FUN_EXPRESSION_LIST2,
    NT_OPT_RETURN_STATEMENT,
    NT_WHILE_LOOP,
    NT_FUNC_CALL,
    NT_STATEMENT_LIST,
    NT_DECL_OPTIONAL_ASSIGNMENT,
    NT_RETURN_STATEMENT,
    NT_TERM,
    NT_EXPRESSION,
    NT_TYPE_LIST2,
    NT_COND_OPT_ELSEIF,
    NT_IDENTIFIER_LIST_WITH_TYPES2,
} nterm_type_t;

typedef enum
{
    T_THEN,
    T_DOUBLE_EQUALS,
    T_EOF,
    T_PERCENT,
    T_TYPE,
    T_DOUBLE_SLASH,
    T_LT,
    T_REQUIRE,
    T_EQUALS,
    T_UNTIL,
    T_RPAREN,
    T_NOT,
    T_FOR,
    T_ASTERISK,
    T_HASH,
    T_LOCAL,
    T_FUNCTION,
    T_BOOL,
    T_BREAK,
    T_ELSE,
    T_LPAREN,
    T_IDENTIFIER,
    T_AND,
    T_IF,
    T_NIL,
    T_END,
    T_DO,
    T_INTEGER,
    T_STRING,
    T_GT,
    T_PLUS,
    T_MINUS,
    T_GTE,
    T_RETURN,
    T_REPEAT,
    T_ELSEIF,
    T_SLASH,
    T_COLON,
    T_NUMBER,
    T_TILDE_EQUALS,
    T_LTE,
    T_GLOBAL,
    T_DOUBLE_DOT,
    T_WHILE,
    T_OR,
    T_COMMA,
    T_CARET,
} term_type_t;

// nterm U term => nut
typedef struct {
    bool is_nterm;
    union {
        nterm_type_t nterm;
        term_type_t term;
    };
} nut_type_t;

typedef struct {
    size_t size;
    nut_type_t *data;
    bool valid;
} exp_list_t;

// hashmap without collisions
typedef struct {
    size_t bucket_count;
    exp_list_t data[];
} parser_table_t;

size_t parser_get_table_index(nterm_type_t nterm, term_type_t term);
const char *nterm_to_readable(nterm_type_t nterm);
const char *term_to_readable(term_type_t term);
int parser_init();
void parser_free();

extern parser_table_t *table;
