/*
 * This file was generated by build_grammar.py, DO NOT MODIFY!
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "parser-generated.h"
#include "error.h"

parser_table_t *table;

static struct {
    void *data;
    size_t size;
    size_t offset;
} mempool;

static void *alloc_tokens(size_t n_tokens)
{
    void *ret = (uint8_t *) mempool.data + mempool.offset;
    mempool.offset += n_tokens * sizeof(nut_type_t);
    return ret;
}
size_t parser_get_table_index(nterm_type_t nterm, term_type_t term)
{
    return ((nterm << 6) + term) % 496;
}
const char *nterm_to_readable(nterm_type_t nterm)
{
    switch(nterm) {
    case NT_EXPRESSION_LIST:
        return "<expression-list>";
    case NT_DECLARATION:
        return "<declaration>";
    case NT_STATEMENT_LIST:
        return "<statement-list>";
    case NT_GLOBAL_STATEMENT_LIST:
        return "<global-statement-list>";
    case NT_FUNC_TYPE_LIST2:
        return "<func-type-list2>";
    case NT_STATEMENT:
        return "<statement>";
    case NT_RET_EXPRESSION_LIST:
        return "<ret-expression-list>";
    case NT_IDENTIFIER_LIST_WITH_TYPES:
        return "<identifier-list-with-types>";
    case NT_IDENTIFIER_LIST_WITH_TYPES2:
        return "<identifier-list-with-types2>";
    case NT_TYPE_LIST2:
        return "<type-list2>";
    case NT_ASSIGNMENT:
        return "<assignment>";
    case NT_GLOBAL_STATEMENT:
        return "<global-statement>";
    case NT_REPEAT_UNTIL:
        return "<repeat-until>";
    case NT_WHILE_LOOP:
        return "<while-loop>";
    case NT_FUNC_TYPE_LIST:
        return "<func-type-list>";
    case NT_FUNC_DECL:
        return "<func-decl>";
    case NT_FUNC_CALL:
        return "<func-call>";
    case NT_EXPRESSION_LIST2:
        return "<expression-list2>";
    case NT_FUN_EXPRESSION_LIST2:
        return "<fun-expression-list2>";
    case NT_FUNC_DEF:
        return "<func-def>";
    case NT_IDENTIFIER_LIST:
        return "<identifier-list>";
    case NT_RET_EXPRESSION_LIST2:
        return "<ret-expression-list2>";
    case NT_IDENTIFIER_WITH_TYPE:
        return "<identifier-with-type>";
    case NT_PROGRAM:
        return "<program>";
    case NT_IDENTIFIER_LIST2:
        return "<identifier-list2>";
    case NT_FOR_LOOP:
        return "<for-loop>";
    case NT_OPTIONAL_FUN_EXPRESSION_LIST:
        return "<optional-fun-expression-list>";
    case NT_RETURN_STATEMENT:
        return "<return-statement>";
    case NT_OPTIONAL_FOR_STEP:
        return "<optional-for-step>";
    case NT_TYPE_LIST:
        return "<type-list>";
    case NT_COND_STATEMENT:
        return "<cond-statement>";
    case NT_DECL_OPTIONAL_ASSIGNMENT:
        return "<decl-optional-assignment>";
    case NT_COND_OPT_ELSEIF:
        return "<cond-opt-elseif>";
    }
    return "<unknown-nterm>";
}
const char *term_to_readable(term_type_t term)
{
    switch(term) {
    case T_RETURN:
        return "return";
    case T_IDENTIFIER:
        return "<identifier>";
    case T_COMMA:
        return ",";
    case T_THEN:
        return "then";
    case T_LT:
        return "<";
    case T_NIL:
        return "nil";
    case T_GLOBAL:
        return "global";
    case T_LPAREN:
        return "(";
    case T_UNTIL:
        return "until";
    case T_NUMBER:
        return "<number>";
    case T_WHILE:
        return "while";
    case T_EXPRESSION:
        return "<expression>";
    case T_ELSE:
        return "else";
    case T_DO:
        return "do";
    case T_COLON:
        return ":";
    case T_ELSEIF:
        return "elseif";
    case T_END:
        return "end";
    case T_TILDE_EQUALS:
        return "~=";
    case T_PLUS:
        return "+";
    case T_LOCAL:
        return "local";
    case T_SLASH:
        return "/";
    case T_BREAK:
        return "break";
    case T_IF:
        return "if";
    case T_STRING:
        return "<string>";
    case T_MINUS:
        return "-";
    case T_HASH:
        return "#";
    case T_TYPE:
        return "<type>";
    case T_FOR:
        return "for";
    case T_BOOL:
        return "<bool>";
    case T_GTE:
        return ">=";
    case T_FUNCTION:
        return "function";
    case T_LTE:
        return "<=";
    case T_DOUBLE_SLASH:
        return "//";
    case T_REQUIRE:
        return "require";
    case T_DOUBLE_EQUALS:
        return "==";
    case T_DOUBLE_DOT:
        return "..";
    case T_ASTERISK:
        return "*";
    case T_CARET:
        return "^";
    case T_REPEAT:
        return "repeat";
    case T_EOF:
        return "$";
    case T_EQUALS:
        return "=";
    case T_PERCENT:
        return "%";
    case T_INTEGER:
        return "<integer>";
    case T_GT:
        return ">";
    case T_RPAREN:
        return ")";
    }
    return "<unknown-term>";
}
int parser_init()
{
    mempool.data = calloc(139, sizeof(nut_type_t));
    if(mempool.data == NULL) {
        return E_INT;
    }
    mempool.size = 139 * sizeof(nut_type_t);

    size_t rule_count = 496;
    table = calloc(1, sizeof(parser_table_t) + rule_count * sizeof(exp_list_t));
    if(table == NULL) {
        return E_INT;
    }

    table->bucket_count = rule_count;
    table->data[17] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[17].data[0].term = T_REQUIRE;
    table->data[17].data[1].term = T_STRING;
    table->data[17].data[2].is_nterm = true;
    table->data[17].data[2].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[193] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[193].data[0].is_nterm = true;
    table->data[193].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[193].data[1].is_nterm = true;
    table->data[193].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[198] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[198].data[0].is_nterm = true;
    table->data[198].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[198].data[1].is_nterm = true;
    table->data[198].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[222] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[222].data[0].is_nterm = true;
    table->data[222].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[222].data[1].is_nterm = true;
    table->data[222].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[231] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[214] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[214].data[0].is_nterm = true;
    table->data[214].data[0].nterm = NT_FUNC_DECL;
    table->data[238] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[238].data[0].is_nterm = true;
    table->data[238].data[0].nterm = NT_FUNC_DEF;
    table->data[209] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[209].data[0].is_nterm = true;
    table->data[209].data[0].nterm = NT_FUNC_CALL;
    table->data[470] = (exp_list_t){ .valid = true, .size = 8, .data = alloc_tokens(8) };
    table->data[470].data[0].term = T_GLOBAL;
    table->data[470].data[1].term = T_IDENTIFIER;
    table->data[470].data[2].term = T_COLON;
    table->data[470].data[3].term = T_FUNCTION;
    table->data[470].data[4].term = T_LPAREN;
    table->data[470].data[5].is_nterm = true;
    table->data[470].data[5].nterm = NT_TYPE_LIST;
    table->data[470].data[6].term = T_RPAREN;
    table->data[470].data[7].is_nterm = true;
    table->data[470].data[7].nterm = NT_FUNC_TYPE_LIST;
    table->data[394] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[394].data[0].term = T_TYPE;
    table->data[394].data[1].is_nterm = true;
    table->data[394].data[1].nterm = NT_TYPE_LIST2;
    table->data[412] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[407] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[82] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[82].data[0].term = T_COMMA;
    table->data[82].data[1].term = T_TYPE;
    table->data[82].data[2].is_nterm = true;
    table->data[82].data[2].nterm = NT_TYPE_LIST2;
    table->data[124] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[119] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[254] = (exp_list_t){ .valid = true, .size = 8, .data = alloc_tokens(8) };
    table->data[254].data[0].term = T_FUNCTION;
    table->data[254].data[1].term = T_IDENTIFIER;
    table->data[254].data[2].term = T_LPAREN;
    table->data[254].data[3].is_nterm = true;
    table->data[254].data[3].nterm = NT_IDENTIFIER_LIST_WITH_TYPES;
    table->data[254].data[4].term = T_RPAREN;
    table->data[254].data[5].is_nterm = true;
    table->data[254].data[5].nterm = NT_FUNC_TYPE_LIST;
    table->data[254].data[6].is_nterm = true;
    table->data[254].data[6].nterm = NT_STATEMENT_LIST;
    table->data[254].data[7].term = T_END;
    table->data[449] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[449].data[0].is_nterm = true;
    table->data[449].data[0].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[449].data[1].is_nterm = true;
    table->data[449].data[1].nterm = NT_IDENTIFIER_LIST_WITH_TYPES2;
    table->data[492] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[487] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[18] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[18].data[0].term = T_COMMA;
    table->data[18].data[1].is_nterm = true;
    table->data[18].data[1].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[18].data[2].is_nterm = true;
    table->data[18].data[2].nterm = NT_IDENTIFIER_LIST_WITH_TYPES2;
    table->data[60] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[55] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[414] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[414].data[0].term = T_COLON;
    table->data[414].data[1].term = T_TYPE;
    table->data[414].data[2].is_nterm = true;
    table->data[414].data[2].nterm = NT_FUNC_TYPE_LIST2;
    table->data[401] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[410] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[419] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[421] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[422] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[439] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[438] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[416] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[427] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[406] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[400] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[430] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[258] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[258].data[0].term = T_COMMA;
    table->data[258].data[1].term = T_TYPE;
    table->data[258].data[2].is_nterm = true;
    table->data[258].data[2].nterm = NT_FUNC_TYPE_LIST2;
    table->data[257] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[266] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[275] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[277] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[278] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[295] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[294] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[272] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[283] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[262] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[256] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[286] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[129] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[129].data[0].is_nterm = true;
    table->data[129].data[0].nterm = NT_STATEMENT;
    table->data[129].data[1].is_nterm = true;
    table->data[129].data[1].nterm = NT_STATEMENT_LIST;
    table->data[138] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[138].data[0].is_nterm = true;
    table->data[138].data[0].nterm = NT_STATEMENT;
    table->data[138].data[1].is_nterm = true;
    table->data[138].data[1].nterm = NT_STATEMENT_LIST;
    table->data[147] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[147].data[0].is_nterm = true;
    table->data[147].data[0].nterm = NT_STATEMENT;
    table->data[147].data[1].is_nterm = true;
    table->data[147].data[1].nterm = NT_STATEMENT_LIST;
    table->data[149] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[149].data[0].is_nterm = true;
    table->data[149].data[0].nterm = NT_STATEMENT;
    table->data[149].data[1].is_nterm = true;
    table->data[149].data[1].nterm = NT_STATEMENT_LIST;
    table->data[150] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[150].data[0].is_nterm = true;
    table->data[150].data[0].nterm = NT_STATEMENT;
    table->data[150].data[1].is_nterm = true;
    table->data[150].data[1].nterm = NT_STATEMENT_LIST;
    table->data[166] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[166].data[0].is_nterm = true;
    table->data[166].data[0].nterm = NT_STATEMENT;
    table->data[166].data[1].is_nterm = true;
    table->data[166].data[1].nterm = NT_STATEMENT_LIST;
    table->data[155] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[155].data[0].is_nterm = true;
    table->data[155].data[0].nterm = NT_STATEMENT;
    table->data[155].data[1].is_nterm = true;
    table->data[155].data[1].nterm = NT_STATEMENT_LIST;
    table->data[128] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[128].data[0].is_nterm = true;
    table->data[128].data[0].nterm = NT_STATEMENT;
    table->data[128].data[1].is_nterm = true;
    table->data[128].data[1].nterm = NT_STATEMENT_LIST;
    table->data[143] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[140] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[144] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[136] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[167] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[342] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[342].data[0].is_nterm = true;
    table->data[342].data[0].nterm = NT_COND_STATEMENT;
    table->data[330] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[330].data[0].is_nterm = true;
    table->data[330].data[0].nterm = NT_WHILE_LOOP;
    table->data[347] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[347].data[0].is_nterm = true;
    table->data[347].data[0].nterm = NT_FOR_LOOP;
    table->data[358] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[358].data[0].is_nterm = true;
    table->data[358].data[0].nterm = NT_REPEAT_UNTIL;
    table->data[339] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[339].data[0].is_nterm = true;
    table->data[339].data[0].nterm = NT_DECLARATION;
    table->data[321] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[321].data[0].is_nterm = true;
    table->data[321].data[0].nterm = NT_ASSIGNMENT;
    table->data[320] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[320].data[0].is_nterm = true;
    table->data[320].data[0].nterm = NT_RETURN_STATEMENT;
    table->data[341] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[341].data[0].term = T_BREAK;
    table->data[454] = (exp_list_t){ .valid = true, .size = 5, .data = alloc_tokens(5) };
    table->data[454].data[0].term = T_IF;
    table->data[454].data[1].term = T_EXPRESSION;
    table->data[454].data[2].term = T_THEN;
    table->data[454].data[3].is_nterm = true;
    table->data[454].data[3].nterm = NT_STATEMENT_LIST;
    table->data[454].data[4].is_nterm = true;
    table->data[454].data[4].nterm = NT_COND_OPT_ELSEIF;
    table->data[79] = (exp_list_t){ .valid = true, .size = 4, .data = alloc_tokens(4) };
    table->data[79].data[0].term = T_ELSEIF;
    table->data[79].data[1].term = T_EXPRESSION;
    table->data[79].data[2].term = T_THEN;
    table->data[79].data[3].is_nterm = true;
    table->data[79].data[3].nterm = NT_COND_OPT_ELSEIF;
    table->data[76] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[76].data[0].term = T_ELSE;
    table->data[76].data[1].is_nterm = true;
    table->data[76].data[1].nterm = NT_STATEMENT_LIST;
    table->data[76].data[2].term = T_END;
    table->data[80] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[80].data[0].term = T_END;
    table->data[346] = (exp_list_t){ .valid = true, .size = 5, .data = alloc_tokens(5) };
    table->data[346].data[0].term = T_WHILE;
    table->data[346].data[1].term = T_EXPRESSION;
    table->data[346].data[2].term = T_DO;
    table->data[346].data[3].is_nterm = true;
    table->data[346].data[3].nterm = NT_STATEMENT_LIST;
    table->data[346].data[4].term = T_END;
    table->data[139] = (exp_list_t){ .valid = true, .size = 10, .data = alloc_tokens(10) };
    table->data[139].data[0].term = T_FOR;
    table->data[139].data[1].term = T_IDENTIFIER;
    table->data[139].data[2].term = T_EQUALS;
    table->data[139].data[3].term = T_EXPRESSION;
    table->data[139].data[4].term = T_COMMA;
    table->data[139].data[5].term = T_EXPRESSION;
    table->data[139].data[6].is_nterm = true;
    table->data[139].data[6].nterm = NT_OPTIONAL_FOR_STEP;
    table->data[139].data[7].term = T_DO;
    table->data[139].data[8].is_nterm = true;
    table->data[139].data[8].nterm = NT_STATEMENT_LIST;
    table->data[139].data[9].term = T_END;
    table->data[306] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[306].data[0].term = T_COMMA;
    table->data[306].data[1].term = T_EXPRESSION;
    table->data[317] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[343] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[310] = (exp_list_t){ .valid = true, .size = 4, .data = alloc_tokens(4) };
    table->data[310].data[0].term = T_REPEAT;
    table->data[310].data[1].is_nterm = true;
    table->data[310].data[1].nterm = NT_STATEMENT_LIST;
    table->data[310].data[2].term = T_UNTIL;
    table->data[310].data[3].term = T_EXPRESSION;
    table->data[83] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[83].data[0].term = T_LOCAL;
    table->data[83].data[1].is_nterm = true;
    table->data[83].data[1].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[83].data[2].is_nterm = true;
    table->data[83].data[2].nterm = NT_DECL_OPTIONAL_ASSIGNMENT;
    table->data[40] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[40].data[0].term = T_EQUALS;
    table->data[40].data[1].term = T_EXPRESSION;
    table->data[15] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[10] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[19] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[21] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[22] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[12] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[16] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[38] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[27] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[0] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[8] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[39] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[417] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[417].data[0].term = T_IDENTIFIER;
    table->data[417].data[1].term = T_COLON;
    table->data[417].data[2].term = T_TYPE;
    table->data[145] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[145].data[0].is_nterm = true;
    table->data[145].data[0].nterm = NT_IDENTIFIER_LIST;
    table->data[145].data[1].term = T_EQUALS;
    table->data[145].data[2].is_nterm = true;
    table->data[145].data[2].nterm = NT_EXPRESSION_LIST;
    table->data[289] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[289].data[0].term = T_IDENTIFIER;
    table->data[289].data[1].is_nterm = true;
    table->data[289].data[1].nterm = NT_IDENTIFIER_LIST2;
    table->data[50] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[50].data[0].term = T_COMMA;
    table->data[50].data[1].term = T_IDENTIFIER;
    table->data[50].data[2].is_nterm = true;
    table->data[50].data[2].nterm = NT_IDENTIFIER_LIST2;
    table->data[88] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[87] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[11] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[11].data[0].term = T_EXPRESSION;
    table->data[11].data[1].is_nterm = true;
    table->data[11].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[98] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[98].data[0].term = T_COMMA;
    table->data[98].data[1].term = T_EXPRESSION;
    table->data[98].data[2].is_nterm = true;
    table->data[98].data[2].nterm = NT_EXPRESSION_LIST2;
    table->data[111] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[97] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[106] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[115] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[117] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[118] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[108] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[112] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[134] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[123] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[96] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[104] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[135] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[240] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[240].data[0].term = T_RETURN;
    table->data[240].data[1].is_nterm = true;
    table->data[240].data[1].nterm = NT_RET_EXPRESSION_LIST;
    table->data[395] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[395].data[0].term = T_EXPRESSION;
    table->data[395].data[1].is_nterm = true;
    table->data[395].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[354] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[354].data[0].term = T_COMMA;
    table->data[354].data[1].term = T_EXPRESSION;
    table->data[354].data[2].is_nterm = true;
    table->data[354].data[2].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[367] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[353] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[362] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[371] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[373] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[374] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[364] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[368] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[390] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[379] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[352] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[360] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[391] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[33] = (exp_list_t){ .valid = true, .size = 4, .data = alloc_tokens(4) };
    table->data[33].data[0].term = T_IDENTIFIER;
    table->data[33].data[1].term = T_LPAREN;
    table->data[33].data[2].is_nterm = true;
    table->data[33].data[2].nterm = NT_OPTIONAL_FUN_EXPRESSION_LIST;
    table->data[33].data[3].term = T_RPAREN;
    table->data[187] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[187].data[0].term = T_EXPRESSION;
    table->data[187].data[1].is_nterm = true;
    table->data[187].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[220] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[215] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[162] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[162].data[0].term = T_COMMA;
    table->data[162].data[1].term = T_EXPRESSION;
    table->data[162].data[2].is_nterm = true;
    table->data[162].data[2].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[204] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[199] = (exp_list_t){ .valid = true, .size = 0 };
    return E_OK;
}
void parser_free()
{
    free(table);
    free(mempool.data);
}
