/*
 * This file was generated by build_grammar.py, DO NOT MODIFY!
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "parser-generated.h"
#include "error.h"

parser_table_t *table;

static struct {
    void *data;
    size_t size;
    size_t offset;
} mempool;

static void *alloc_tokens(size_t n_tokens)
{
    void *ret = (uint8_t *) mempool.data + mempool.offset;
    mempool.offset += n_tokens * sizeof(nut_type_t);
    return ret;
}
size_t parser_get_table_index(nterm_type_t nterm, term_type_t term)
{
    return ((nterm << 6) + term) % 1123;
}
const char *nterm_to_readable(nterm_type_t nterm)
{
    switch(nterm) {
    case NT_PROGRAM:
        return "<program>";
    case NT_TYPE_LIST:
        return "<type-list>";
    case NT_COND_STATEMENT:
        return "<cond-statement>";
    case NT_RET_EXPRESSION_LIST:
        return "<ret-expression-list>";
    case NT_OPTIONAL_FOR_STEP:
        return "<optional-for-step>";
    case NT_REPEAT_UNTIL:
        return "<repeat-until>";
    case NT_OPT_BINOP:
        return "<opt-binop>";
    case NT_GLOBAL_STATEMENT:
        return "<global-statement>";
    case NT_IDENTIFIER_LIST_WITH_TYPES:
        return "<identifier-list-with-types>";
    case NT_GLOBAL_STATEMENT_LIST:
        return "<global-statement-list>";
    case NT_EXPRESSION_LIST:
        return "<expression-list>";
    case NT_STATEMENT:
        return "<statement>";
    case NT_FOR_LOOP:
        return "<for-loop>";
    case NT_FUNC_DECL:
        return "<func-decl>";
    case NT_FUNC_TYPE_LIST2:
        return "<func-type-list2>";
    case NT_STATEMENT_LIST2:
        return "<statement-list2>";
    case NT_EXPRESSION_LIST2:
        return "<expression-list2>";
    case NT_FUNC_TYPE_LIST:
        return "<func-type-list>";
    case NT_DECLARATION:
        return "<declaration>";
    case NT_RET_EXPRESSION_LIST2:
        return "<ret-expression-list2>";
    case NT_IDENTIFIER_LIST:
        return "<identifier-list>";
    case NT_FUNC_DEF:
        return "<func-def>";
    case NT_IDENTIFIER_LIST2:
        return "<identifier-list2>";
    case NT_UNOP:
        return "<unop>";
    case NT_ASSIGNMENT:
        return "<assignment>";
    case NT_IDENTIFIER_WITH_TYPE:
        return "<identifier-with-type>";
    case NT_PAREN_EXP_LIST_OR_ID_LIST2:
        return "<paren-exp-list-or-id-list2>";
    case NT_OPTIONAL_FUN_EXPRESSION_LIST:
        return "<optional-fun-expression-list>";
    case NT_BINOP:
        return "<binop>";
    case NT_FUN_EXPRESSION_LIST2:
        return "<fun-expression-list2>";
    case NT_OPT_RETURN_STATEMENT:
        return "<opt-return-statement>";
    case NT_WHILE_LOOP:
        return "<while-loop>";
    case NT_FUNC_CALL:
        return "<func-call>";
    case NT_STATEMENT_LIST:
        return "<statement-list>";
    case NT_DECL_OPTIONAL_ASSIGNMENT:
        return "<decl-optional-assignment>";
    case NT_RETURN_STATEMENT:
        return "<return-statement>";
    case NT_TERM:
        return "<term>";
    case NT_EXPRESSION:
        return "<expression>";
    case NT_TYPE_LIST2:
        return "<type-list2>";
    case NT_COND_OPT_ELSEIF:
        return "<cond-opt-elseif>";
    case NT_IDENTIFIER_LIST_WITH_TYPES2:
        return "<identifier-list-with-types2>";
    }
    return "<unknown-nterm>";
}
const char *term_to_readable(term_type_t term)
{
    switch(term) {
    case T_THEN:
        return "then";
    case T_DOUBLE_EQUALS:
        return "==";
    case T_EOF:
        return "$";
    case T_PERCENT:
        return "%";
    case T_TYPE:
        return "<type>";
    case T_DOUBLE_SLASH:
        return "//";
    case T_LT:
        return "<";
    case T_REQUIRE:
        return "require";
    case T_EQUALS:
        return "=";
    case T_UNTIL:
        return "until";
    case T_RPAREN:
        return ")";
    case T_NOT:
        return "not";
    case T_FOR:
        return "for";
    case T_ASTERISK:
        return "*";
    case T_HASH:
        return "#";
    case T_LOCAL:
        return "local";
    case T_FUNCTION:
        return "function";
    case T_BOOL:
        return "<bool>";
    case T_BREAK:
        return "break";
    case T_ELSE:
        return "else";
    case T_LPAREN:
        return "(";
    case T_IDENTIFIER:
        return "<identifier>";
    case T_AND:
        return "and";
    case T_IF:
        return "if";
    case T_NIL:
        return "nil";
    case T_END:
        return "end";
    case T_DO:
        return "do";
    case T_INTEGER:
        return "<integer>";
    case T_STRING:
        return "<string>";
    case T_GT:
        return ">";
    case T_PLUS:
        return "+";
    case T_MINUS:
        return "-";
    case T_GTE:
        return ">=";
    case T_RETURN:
        return "return";
    case T_REPEAT:
        return "repeat";
    case T_ELSEIF:
        return "elseif";
    case T_SLASH:
        return "/";
    case T_COLON:
        return ":";
    case T_NUMBER:
        return "<number>";
    case T_TILDE_EQUALS:
        return "~=";
    case T_LTE:
        return "<=";
    case T_GLOBAL:
        return "global";
    case T_DOUBLE_DOT:
        return "..";
    case T_WHILE:
        return "while";
    case T_OR:
        return "or";
    case T_COMMA:
        return ",";
    case T_CARET:
        return "^";
    }
    return "<unknown-term>";
}
int parser_init()
{
    mempool.offset = 0;
    mempool.data = calloc(311, sizeof(nut_type_t));
    if(mempool.data == NULL) {
        return E_INT;
    }
    mempool.size = 311 * sizeof(nut_type_t);

    size_t rule_count = 1123;
    table = calloc(1, sizeof(parser_table_t) + rule_count * sizeof(exp_list_t));
    if(table == NULL) {
        return E_INT;
    }

    table->bucket_count = rule_count;
    table->data[7] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[7].data[0].term = T_REQUIRE;
    table->data[7].data[1].term = T_STRING;
    table->data[7].data[2].is_nterm = true;
    table->data[7].data[2].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[592] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[592].data[0].is_nterm = true;
    table->data[592].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[592].data[1].is_nterm = true;
    table->data[592].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[597] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[597].data[0].is_nterm = true;
    table->data[597].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[597].data[1].is_nterm = true;
    table->data[597].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[617] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[617].data[0].is_nterm = true;
    table->data[617].data[0].nterm = NT_GLOBAL_STATEMENT;
    table->data[617].data[1].is_nterm = true;
    table->data[617].data[1].nterm = NT_GLOBAL_STATEMENT_LIST;
    table->data[578] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[489] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[489].data[0].is_nterm = true;
    table->data[489].data[0].nterm = NT_FUNC_DECL;
    table->data[464] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[464].data[0].is_nterm = true;
    table->data[464].data[0].nterm = NT_FUNC_DEF;
    table->data[469] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[469].data[0].is_nterm = true;
    table->data[469].data[0].nterm = NT_FUNC_CALL;
    table->data[873] = (exp_list_t){ .valid = true, .size = 8, .data = alloc_tokens(8) };
    table->data[873].data[0].term = T_GLOBAL;
    table->data[873].data[1].term = T_IDENTIFIER;
    table->data[873].data[2].term = T_COLON;
    table->data[873].data[3].term = T_FUNCTION;
    table->data[873].data[4].term = T_LPAREN;
    table->data[873].data[5].is_nterm = true;
    table->data[873].data[5].nterm = NT_TYPE_LIST;
    table->data[873].data[6].term = T_RPAREN;
    table->data[873].data[7].is_nterm = true;
    table->data[873].data[7].nterm = NT_FUNC_TYPE_LIST;
    table->data[68] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[68].data[0].term = T_TYPE;
    table->data[68].data[1].is_nterm = true;
    table->data[68].data[1].nterm = NT_TYPE_LIST2;
    table->data[74] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[66] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[231] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[231].data[0].term = T_COMMA;
    table->data[231].data[1].term = T_TYPE;
    table->data[231].data[2].is_nterm = true;
    table->data[231].data[2].nterm = NT_TYPE_LIST2;
    table->data[196] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[188] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[237] = (exp_list_t){ .valid = true, .size = 8, .data = alloc_tokens(8) };
    table->data[237].data[0].term = T_FUNCTION;
    table->data[237].data[1].term = T_IDENTIFIER;
    table->data[237].data[2].term = T_LPAREN;
    table->data[237].data[3].is_nterm = true;
    table->data[237].data[3].nterm = NT_IDENTIFIER_LIST_WITH_TYPES;
    table->data[237].data[4].term = T_RPAREN;
    table->data[237].data[5].is_nterm = true;
    table->data[237].data[5].nterm = NT_FUNC_TYPE_LIST;
    table->data[237].data[6].is_nterm = true;
    table->data[237].data[6].nterm = NT_STATEMENT_LIST;
    table->data[237].data[7].term = T_END;
    table->data[533] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[533].data[0].is_nterm = true;
    table->data[533].data[0].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[533].data[1].is_nterm = true;
    table->data[533].data[1].nterm = NT_IDENTIFIER_LIST_WITH_TYPES2;
    table->data[522] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[514] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[359] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[359].data[0].term = T_COMMA;
    table->data[359].data[1].is_nterm = true;
    table->data[359].data[1].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[359].data[2].is_nterm = true;
    table->data[359].data[2].nterm = NT_IDENTIFIER_LIST_WITH_TYPES2;
    table->data[324] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[316] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[2] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[2].data[0].term = T_COLON;
    table->data[2].data[1].term = T_TYPE;
    table->data[2].data[2].is_nterm = true;
    table->data[2].data[2].nterm = NT_FUNC_TYPE_LIST2;
    table->data[1111] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1090] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1113] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[8] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1104] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[6] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1109] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1122] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1103] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1121] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1100] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1106] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[941] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[941].data[0].term = T_COMMA;
    table->data[941].data[1].term = T_TYPE;
    table->data[941].data[2].is_nterm = true;
    table->data[941].data[2].nterm = NT_FUNC_TYPE_LIST2;
    table->data[919] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[898] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[921] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[939] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[912] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[937] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[917] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[930] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[911] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[929] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[908] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[914] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1012] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1012].data[0].is_nterm = true;
    table->data[1012].data[0].nterm = NT_STATEMENT;
    table->data[1012].data[1].is_nterm = true;
    table->data[1012].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1012].data[2].is_nterm = true;
    table->data[1012].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1032] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1032].data[0].is_nterm = true;
    table->data[1032].data[0].nterm = NT_STATEMENT;
    table->data[1032].data[1].is_nterm = true;
    table->data[1032].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1032].data[2].is_nterm = true;
    table->data[1032].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1010] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1010].data[0].is_nterm = true;
    table->data[1010].data[0].nterm = NT_STATEMENT;
    table->data[1010].data[1].is_nterm = true;
    table->data[1010].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1010].data[2].is_nterm = true;
    table->data[1010].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1023] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1023].data[0].is_nterm = true;
    table->data[1023].data[0].nterm = NT_STATEMENT;
    table->data[1023].data[1].is_nterm = true;
    table->data[1023].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1023].data[2].is_nterm = true;
    table->data[1023].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1004] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1004].data[0].is_nterm = true;
    table->data[1004].data[0].nterm = NT_STATEMENT;
    table->data[1004].data[1].is_nterm = true;
    table->data[1004].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1004].data[2].is_nterm = true;
    table->data[1004].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1001] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1001].data[0].is_nterm = true;
    table->data[1001].data[0].nterm = NT_STATEMENT;
    table->data[1001].data[1].is_nterm = true;
    table->data[1001].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1001].data[2].is_nterm = true;
    table->data[1001].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1007] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1007].data[0].is_nterm = true;
    table->data[1007].data[0].nterm = NT_STATEMENT;
    table->data[1007].data[1].is_nterm = true;
    table->data[1007].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1007].data[2].is_nterm = true;
    table->data[1007].data[2].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[1022] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[1022].data[0].is_nterm = true;
    table->data[1022].data[0].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[998] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1024] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1014] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1008] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[991] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[991].data[0].is_nterm = true;
    table->data[991].data[0].nterm = NT_OPT_RETURN_STATEMENT;
    table->data[983] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[983].data[0].is_nterm = true;
    table->data[983].data[0].nterm = NT_STATEMENT;
    table->data[983].data[1].is_nterm = true;
    table->data[983].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[1003] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[1003].data[0].is_nterm = true;
    table->data[1003].data[0].nterm = NT_STATEMENT;
    table->data[1003].data[1].is_nterm = true;
    table->data[1003].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[981] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[981].data[0].is_nterm = true;
    table->data[981].data[0].nterm = NT_STATEMENT;
    table->data[981].data[1].is_nterm = true;
    table->data[981].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[994] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[994].data[0].is_nterm = true;
    table->data[994].data[0].nterm = NT_STATEMENT;
    table->data[994].data[1].is_nterm = true;
    table->data[994].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[975] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[975].data[0].is_nterm = true;
    table->data[975].data[0].nterm = NT_STATEMENT;
    table->data[975].data[1].is_nterm = true;
    table->data[975].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[972] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[972].data[0].is_nterm = true;
    table->data[972].data[0].nterm = NT_STATEMENT;
    table->data[972].data[1].is_nterm = true;
    table->data[972].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[978] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[978].data[0].is_nterm = true;
    table->data[978].data[0].nterm = NT_STATEMENT;
    table->data[978].data[1].is_nterm = true;
    table->data[978].data[1].nterm = NT_STATEMENT_LIST2;
    table->data[995] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[979] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[993] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[985] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[969] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[962] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[727] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[727].data[0].is_nterm = true;
    table->data[727].data[0].nterm = NT_COND_STATEMENT;
    table->data[747] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[747].data[0].is_nterm = true;
    table->data[747].data[0].nterm = NT_WHILE_LOOP;
    table->data[716] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[716].data[0].is_nterm = true;
    table->data[716].data[0].nterm = NT_FOR_LOOP;
    table->data[738] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[738].data[0].is_nterm = true;
    table->data[738].data[0].nterm = NT_REPEAT_UNTIL;
    table->data[719] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[719].data[0].is_nterm = true;
    table->data[719].data[0].nterm = NT_DECLARATION;
    table->data[725] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[725].data[0].term = T_IDENTIFIER;
    table->data[725].data[1].is_nterm = true;
    table->data[725].data[1].nterm = NT_PAREN_EXP_LIST_OR_ID_LIST2;
    table->data[722] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[722].data[0].term = T_BREAK;
    table->data[561] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[561].data[0].term = T_LPAREN;
    table->data[561].data[1].is_nterm = true;
    table->data[561].data[1].nterm = NT_OPTIONAL_FUN_EXPRESSION_LIST;
    table->data[561].data[2].term = T_RPAREN;
    table->data[586] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[586].data[0].is_nterm = true;
    table->data[586].data[0].nterm = NT_IDENTIFIER_LIST2;
    table->data[586].data[1].term = T_EQUALS;
    table->data[586].data[2].is_nterm = true;
    table->data[586].data[2].nterm = NT_EXPRESSION_LIST;
    table->data[549] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[549].data[0].is_nterm = true;
    table->data[549].data[0].nterm = NT_IDENTIFIER_LIST2;
    table->data[549].data[1].term = T_EQUALS;
    table->data[549].data[2].is_nterm = true;
    table->data[549].data[2].nterm = NT_EXPRESSION_LIST;
    table->data[151] = (exp_list_t){ .valid = true, .size = 5, .data = alloc_tokens(5) };
    table->data[151].data[0].term = T_IF;
    table->data[151].data[1].is_nterm = true;
    table->data[151].data[1].nterm = NT_EXPRESSION;
    table->data[151].data[2].term = T_THEN;
    table->data[151].data[3].is_nterm = true;
    table->data[151].data[3].nterm = NT_STATEMENT_LIST;
    table->data[151].data[4].is_nterm = true;
    table->data[151].data[4].nterm = NT_COND_OPT_ELSEIF;
    table->data[285] = (exp_list_t){ .valid = true, .size = 5, .data = alloc_tokens(5) };
    table->data[285].data[0].term = T_ELSEIF;
    table->data[285].data[1].is_nterm = true;
    table->data[285].data[1].nterm = NT_EXPRESSION;
    table->data[285].data[2].term = T_THEN;
    table->data[285].data[3].is_nterm = true;
    table->data[285].data[3].nterm = NT_STATEMENT_LIST;
    table->data[285].data[4].is_nterm = true;
    table->data[285].data[4].nterm = NT_COND_OPT_ELSEIF;
    table->data[269] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[269].data[0].term = T_ELSE;
    table->data[269].data[1].is_nterm = true;
    table->data[269].data[1].nterm = NT_STATEMENT_LIST;
    table->data[269].data[2].term = T_END;
    table->data[275] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[275].data[0].term = T_END;
    table->data[904] = (exp_list_t){ .valid = true, .size = 5, .data = alloc_tokens(5) };
    table->data[904].data[0].term = T_WHILE;
    table->data[904].data[1].is_nterm = true;
    table->data[904].data[1].nterm = NT_EXPRESSION;
    table->data[904].data[2].term = T_DO;
    table->data[904].data[3].is_nterm = true;
    table->data[904].data[3].nterm = NT_STATEMENT_LIST;
    table->data[904].data[4].term = T_END;
    table->data[780] = (exp_list_t){ .valid = true, .size = 10, .data = alloc_tokens(10) };
    table->data[780].data[0].term = T_FOR;
    table->data[780].data[1].term = T_IDENTIFIER;
    table->data[780].data[2].term = T_EQUALS;
    table->data[780].data[3].is_nterm = true;
    table->data[780].data[3].nterm = NT_EXPRESSION;
    table->data[780].data[4].term = T_COMMA;
    table->data[780].data[5].is_nterm = true;
    table->data[780].data[5].nterm = NT_EXPRESSION;
    table->data[780].data[6].is_nterm = true;
    table->data[780].data[6].nterm = NT_OPTIONAL_FOR_STEP;
    table->data[780].data[7].term = T_DO;
    table->data[780].data[8].is_nterm = true;
    table->data[780].data[8].nterm = NT_STATEMENT_LIST;
    table->data[780].data[9].term = T_END;
    table->data[301] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[301].data[0].term = T_COMMA;
    table->data[301].data[1].is_nterm = true;
    table->data[301].data[1].nterm = NT_EXPRESSION;
    table->data[282] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[258] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[354] = (exp_list_t){ .valid = true, .size = 4, .data = alloc_tokens(4) };
    table->data[354].data[0].term = T_REPEAT;
    table->data[354].data[1].is_nterm = true;
    table->data[354].data[1].nterm = NT_STATEMENT_LIST;
    table->data[354].data[2].term = T_UNTIL;
    table->data[354].data[3].is_nterm = true;
    table->data[354].data[3].nterm = NT_EXPRESSION;
    table->data[44] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[44].data[0].term = T_LOCAL;
    table->data[44].data[1].is_nterm = true;
    table->data[44].data[1].nterm = NT_IDENTIFIER_WITH_TYPE;
    table->data[44].data[2].is_nterm = true;
    table->data[44].data[2].nterm = NT_DECL_OPTIONAL_ASSIGNMENT;
    table->data[1061] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[1061].data[0].term = T_EQUALS;
    table->data[1061].data[1].is_nterm = true;
    table->data[1061].data[1].nterm = NT_EXPRESSION;
    table->data[1076] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1088] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1078] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1096] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1062] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1074] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1087] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1068] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1086] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1065] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1071] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1072] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1055] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[498] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[498].data[0].term = T_IDENTIFIER;
    table->data[498].data[1].term = T_COLON;
    table->data[498].data[2].term = T_TYPE;
    table->data[434] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[434].data[0].is_nterm = true;
    table->data[434].data[0].nterm = NT_IDENTIFIER_LIST;
    table->data[434].data[1].term = T_EQUALS;
    table->data[434].data[2].is_nterm = true;
    table->data[434].data[2].nterm = NT_EXPRESSION_LIST;
    table->data[178] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[178].data[0].term = T_IDENTIFIER;
    table->data[178].data[1].is_nterm = true;
    table->data[178].data[1].nterm = NT_IDENTIFIER_LIST2;
    table->data[330] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[330].data[0].term = T_COMMA;
    table->data[330].data[1].term = T_IDENTIFIER;
    table->data[330].data[2].is_nterm = true;
    table->data[330].data[2].nterm = NT_IDENTIFIER_LIST2;
    table->data[293] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[287] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[664] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[664].data[0].is_nterm = true;
    table->data[664].data[0].nterm = NT_EXPRESSION;
    table->data[664].data[1].is_nterm = true;
    table->data[664].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[668] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[668].data[0].is_nterm = true;
    table->data[668].data[0].nterm = NT_EXPRESSION;
    table->data[668].data[1].is_nterm = true;
    table->data[668].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[661] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[661].data[0].is_nterm = true;
    table->data[661].data[0].nterm = NT_EXPRESSION;
    table->data[661].data[1].is_nterm = true;
    table->data[661].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[660] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[660].data[0].is_nterm = true;
    table->data[660].data[0].nterm = NT_EXPRESSION;
    table->data[660].data[1].is_nterm = true;
    table->data[660].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[667] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[667].data[0].is_nterm = true;
    table->data[667].data[0].nterm = NT_EXPRESSION;
    table->data[667].data[1].is_nterm = true;
    table->data[667].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[651] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[651].data[0].is_nterm = true;
    table->data[651].data[0].nterm = NT_EXPRESSION;
    table->data[651].data[1].is_nterm = true;
    table->data[651].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[654] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[654].data[0].is_nterm = true;
    table->data[654].data[0].nterm = NT_EXPRESSION;
    table->data[654].data[1].is_nterm = true;
    table->data[654].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[671] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[671].data[0].is_nterm = true;
    table->data[671].data[0].nterm = NT_EXPRESSION;
    table->data[671].data[1].is_nterm = true;
    table->data[671].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[657] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[657].data[0].is_nterm = true;
    table->data[657].data[0].nterm = NT_EXPRESSION;
    table->data[657].data[1].is_nterm = true;
    table->data[657].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[678] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[678].data[0].is_nterm = true;
    table->data[678].data[0].nterm = NT_EXPRESSION;
    table->data[678].data[1].is_nterm = true;
    table->data[678].data[1].nterm = NT_EXPRESSION_LIST2;
    table->data[1069] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[1069].data[0].term = T_COMMA;
    table->data[1069].data[1].is_nterm = true;
    table->data[1069].data[1].nterm = NT_EXPRESSION;
    table->data[1069].data[2].is_nterm = true;
    table->data[1069].data[2].nterm = NT_EXPRESSION_LIST2;
    table->data[1047] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1059] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1049] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1067] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1033] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1045] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1058] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1039] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1057] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1036] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1042] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1043] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[1026] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[830] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[830].data[0].is_nterm = true;
    table->data[830].data[0].nterm = NT_RETURN_STATEMENT;
    table->data[832] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[822] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[806] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[816] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[799] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[27] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[27].data[0].term = T_RETURN;
    table->data[27].data[1].is_nterm = true;
    table->data[27].data[1].nterm = NT_RET_EXPRESSION_LIST;
    table->data[216] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[216].data[0].is_nterm = true;
    table->data[216].data[0].nterm = NT_EXPRESSION;
    table->data[216].data[1].is_nterm = true;
    table->data[216].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[220] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[220].data[0].is_nterm = true;
    table->data[220].data[0].nterm = NT_EXPRESSION;
    table->data[220].data[1].is_nterm = true;
    table->data[220].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[213] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[213].data[0].is_nterm = true;
    table->data[213].data[0].nterm = NT_EXPRESSION;
    table->data[213].data[1].is_nterm = true;
    table->data[213].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[212] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[212].data[0].is_nterm = true;
    table->data[212].data[0].nterm = NT_EXPRESSION;
    table->data[212].data[1].is_nterm = true;
    table->data[212].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[219] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[219].data[0].is_nterm = true;
    table->data[219].data[0].nterm = NT_EXPRESSION;
    table->data[219].data[1].is_nterm = true;
    table->data[219].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[203] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[203].data[0].is_nterm = true;
    table->data[203].data[0].nterm = NT_EXPRESSION;
    table->data[203].data[1].is_nterm = true;
    table->data[203].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[206] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[206].data[0].is_nterm = true;
    table->data[206].data[0].nterm = NT_EXPRESSION;
    table->data[206].data[1].is_nterm = true;
    table->data[206].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[223] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[223].data[0].is_nterm = true;
    table->data[223].data[0].nterm = NT_EXPRESSION;
    table->data[223].data[1].is_nterm = true;
    table->data[223].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[209] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[209].data[0].is_nterm = true;
    table->data[209].data[0].nterm = NT_EXPRESSION;
    table->data[209].data[1].is_nterm = true;
    table->data[209].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[230] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[230].data[0].is_nterm = true;
    table->data[230].data[0].nterm = NT_EXPRESSION;
    table->data[230].data[1].is_nterm = true;
    table->data[230].data[1].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[227] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[217] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[201] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[211] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[194] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[138] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[138].data[0].term = T_COMMA;
    table->data[138].data[1].is_nterm = true;
    table->data[138].data[1].nterm = NT_EXPRESSION;
    table->data[138].data[2].is_nterm = true;
    table->data[138].data[2].nterm = NT_RET_EXPRESSION_LIST2;
    table->data[128] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[118] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[102] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[112] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[95] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[946] = (exp_list_t){ .valid = true, .size = 4, .data = alloc_tokens(4) };
    table->data[946].data[0].term = T_IDENTIFIER;
    table->data[946].data[1].term = T_LPAREN;
    table->data[946].data[2].is_nterm = true;
    table->data[946].data[2].nterm = NT_OPTIONAL_FUN_EXPRESSION_LIST;
    table->data[946].data[3].term = T_RPAREN;
    table->data[629] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[629].data[0].is_nterm = true;
    table->data[629].data[0].nterm = NT_EXPRESSION;
    table->data[629].data[1].is_nterm = true;
    table->data[629].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[633] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[633].data[0].is_nterm = true;
    table->data[633].data[0].nterm = NT_EXPRESSION;
    table->data[633].data[1].is_nterm = true;
    table->data[633].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[626] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[626].data[0].is_nterm = true;
    table->data[626].data[0].nterm = NT_EXPRESSION;
    table->data[626].data[1].is_nterm = true;
    table->data[626].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[625] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[625].data[0].is_nterm = true;
    table->data[625].data[0].nterm = NT_EXPRESSION;
    table->data[625].data[1].is_nterm = true;
    table->data[625].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[632] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[632].data[0].is_nterm = true;
    table->data[632].data[0].nterm = NT_EXPRESSION;
    table->data[632].data[1].is_nterm = true;
    table->data[632].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[616] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[616].data[0].is_nterm = true;
    table->data[616].data[0].nterm = NT_EXPRESSION;
    table->data[616].data[1].is_nterm = true;
    table->data[616].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[619] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[619].data[0].is_nterm = true;
    table->data[619].data[0].nterm = NT_EXPRESSION;
    table->data[619].data[1].is_nterm = true;
    table->data[619].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[636] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[636].data[0].is_nterm = true;
    table->data[636].data[0].nterm = NT_EXPRESSION;
    table->data[636].data[1].is_nterm = true;
    table->data[636].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[622] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[622].data[0].is_nterm = true;
    table->data[622].data[0].nterm = NT_EXPRESSION;
    table->data[622].data[1].is_nterm = true;
    table->data[622].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[643] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[643].data[0].is_nterm = true;
    table->data[643].data[0].nterm = NT_EXPRESSION;
    table->data[643].data[1].is_nterm = true;
    table->data[643].data[1].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[615] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[607] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[778] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[778].data[0].term = T_COMMA;
    table->data[778].data[1].is_nterm = true;
    table->data[778].data[1].nterm = NT_EXPRESSION;
    table->data[778].data[2].is_nterm = true;
    table->data[778].data[2].nterm = NT_FUN_EXPRESSION_LIST2;
    table->data[743] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[735] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[146] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[146].data[0].is_nterm = true;
    table->data[146].data[0].nterm = NT_TERM;
    table->data[146].data[1].is_nterm = true;
    table->data[146].data[1].nterm = NT_OPT_BINOP;
    table->data[150] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[150].data[0].is_nterm = true;
    table->data[150].data[0].nterm = NT_TERM;
    table->data[150].data[1].is_nterm = true;
    table->data[150].data[1].nterm = NT_OPT_BINOP;
    table->data[143] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[143].data[0].is_nterm = true;
    table->data[143].data[0].nterm = NT_TERM;
    table->data[143].data[1].is_nterm = true;
    table->data[143].data[1].nterm = NT_OPT_BINOP;
    table->data[142] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[142].data[0].is_nterm = true;
    table->data[142].data[0].nterm = NT_TERM;
    table->data[142].data[1].is_nterm = true;
    table->data[142].data[1].nterm = NT_OPT_BINOP;
    table->data[139] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[139].data[0].is_nterm = true;
    table->data[139].data[0].nterm = NT_TERM;
    table->data[139].data[1].is_nterm = true;
    table->data[139].data[1].nterm = NT_OPT_BINOP;
    table->data[149] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[149].data[0].is_nterm = true;
    table->data[149].data[0].nterm = NT_TERM;
    table->data[149].data[1].is_nterm = true;
    table->data[149].data[1].nterm = NT_OPT_BINOP;
    table->data[160] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[160].data[0].is_nterm = true;
    table->data[160].data[0].nterm = NT_TERM;
    table->data[160].data[1].is_nterm = true;
    table->data[160].data[1].nterm = NT_OPT_BINOP;
    table->data[133] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[133].data[0].is_nterm = true;
    table->data[133].data[0].nterm = NT_UNOP;
    table->data[133].data[1].is_nterm = true;
    table->data[133].data[1].nterm = NT_TERM;
    table->data[133].data[2].is_nterm = true;
    table->data[133].data[2].nterm = NT_OPT_BINOP;
    table->data[136] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[136].data[0].is_nterm = true;
    table->data[136].data[0].nterm = NT_UNOP;
    table->data[136].data[1].is_nterm = true;
    table->data[136].data[1].nterm = NT_TERM;
    table->data[136].data[2].is_nterm = true;
    table->data[136].data[2].nterm = NT_OPT_BINOP;
    table->data[153] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[153].data[0].is_nterm = true;
    table->data[153].data[0].nterm = NT_UNOP;
    table->data[153].data[1].is_nterm = true;
    table->data[153].data[1].nterm = NT_TERM;
    table->data[153].data[2].is_nterm = true;
    table->data[153].data[2].nterm = NT_OPT_BINOP;
    table->data[397] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[397].data[0].is_nterm = true;
    table->data[397].data[0].nterm = NT_BINOP;
    table->data[397].data[1].is_nterm = true;
    table->data[397].data[1].nterm = NT_EXPRESSION;
    table->data[423] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[423].data[0].is_nterm = true;
    table->data[423].data[0].nterm = NT_BINOP;
    table->data[423].data[1].is_nterm = true;
    table->data[423].data[1].nterm = NT_EXPRESSION;
    table->data[385] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[385].data[0].is_nterm = true;
    table->data[385].data[0].nterm = NT_BINOP;
    table->data[385].data[1].is_nterm = true;
    table->data[385].data[1].nterm = NT_EXPRESSION;
    table->data[413] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[413].data[0].is_nterm = true;
    table->data[413].data[0].nterm = NT_BINOP;
    table->data[413].data[1].is_nterm = true;
    table->data[413].data[1].nterm = NT_EXPRESSION;
    table->data[390] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[390].data[0].is_nterm = true;
    table->data[390].data[0].nterm = NT_BINOP;
    table->data[390].data[1].is_nterm = true;
    table->data[390].data[1].nterm = NT_EXPRESSION;
    table->data[424] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[424].data[0].is_nterm = true;
    table->data[424].data[0].nterm = NT_BINOP;
    table->data[424].data[1].is_nterm = true;
    table->data[424].data[1].nterm = NT_EXPRESSION;
    table->data[430] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[430].data[0].is_nterm = true;
    table->data[430].data[0].nterm = NT_BINOP;
    table->data[430].data[1].is_nterm = true;
    table->data[430].data[1].nterm = NT_EXPRESSION;
    table->data[389] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[389].data[0].is_nterm = true;
    table->data[389].data[0].nterm = NT_BINOP;
    table->data[389].data[1].is_nterm = true;
    table->data[389].data[1].nterm = NT_EXPRESSION;
    table->data[426] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[426].data[0].is_nterm = true;
    table->data[426].data[0].nterm = NT_BINOP;
    table->data[426].data[1].is_nterm = true;
    table->data[426].data[1].nterm = NT_EXPRESSION;
    table->data[414] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[414].data[0].is_nterm = true;
    table->data[414].data[0].nterm = NT_BINOP;
    table->data[414].data[1].is_nterm = true;
    table->data[414].data[1].nterm = NT_EXPRESSION;
    table->data[415] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[415].data[0].is_nterm = true;
    table->data[415].data[0].nterm = NT_BINOP;
    table->data[415].data[1].is_nterm = true;
    table->data[415].data[1].nterm = NT_EXPRESSION;
    table->data[428] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[428].data[0].is_nterm = true;
    table->data[428].data[0].nterm = NT_BINOP;
    table->data[428].data[1].is_nterm = true;
    table->data[428].data[1].nterm = NT_EXPRESSION;
    table->data[416] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[416].data[0].is_nterm = true;
    table->data[416].data[0].nterm = NT_BINOP;
    table->data[416].data[1].is_nterm = true;
    table->data[416].data[1].nterm = NT_EXPRESSION;
    table->data[406] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[406].data[0].is_nterm = true;
    table->data[406].data[0].nterm = NT_BINOP;
    table->data[406].data[1].is_nterm = true;
    table->data[406].data[1].nterm = NT_EXPRESSION;
    table->data[387] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[387].data[0].is_nterm = true;
    table->data[387].data[0].nterm = NT_BINOP;
    table->data[387].data[1].is_nterm = true;
    table->data[387].data[1].nterm = NT_EXPRESSION;
    table->data[420] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[420].data[0].is_nterm = true;
    table->data[420].data[0].nterm = NT_BINOP;
    table->data[420].data[1].is_nterm = true;
    table->data[420].data[1].nterm = NT_EXPRESSION;
    table->data[421] = (exp_list_t){ .valid = true, .size = 2, .data = alloc_tokens(2) };
    table->data[421].data[0].is_nterm = true;
    table->data[421].data[0].nterm = NT_BINOP;
    table->data[421].data[1].is_nterm = true;
    table->data[421].data[1].nterm = NT_EXPRESSION;
    table->data[407] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[429] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[409] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[427] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[393] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[405] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[418] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[399] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[403] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[384] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[419] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[410] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[417] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[396] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[394] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[402] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[386] = (exp_list_t){ .valid = true, .size = 0 };
    table->data[699] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[699].data[0].term = T_PLUS;
    table->data[700] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[700].data[0].term = T_MINUS;
    table->data[682] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[682].data[0].term = T_ASTERISK;
    table->data[705] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[705].data[0].term = T_SLASH;
    table->data[672] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[672].data[0].term = T_PERCENT;
    table->data[715] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[715].data[0].term = T_CARET;
    table->data[674] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[674].data[0].term = T_DOUBLE_SLASH;
    table->data[711] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[711].data[0].term = T_DOUBLE_DOT;
    table->data[706] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[706].data[0].term = T_COLON;
    table->data[675] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[675].data[0].term = T_LT;
    table->data[698] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[698].data[0].term = T_GT;
    table->data[709] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[709].data[0].term = T_LTE;
    table->data[701] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[701].data[0].term = T_GTE;
    table->data[670] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[670].data[0].term = T_DOUBLE_EQUALS;
    table->data[708] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[708].data[0].term = T_TILDE_EQUALS;
    table->data[691] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[691].data[0].term = T_AND;
    table->data[713] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[713].data[0].term = T_OR;
    table->data[380] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[380].data[0].term = T_MINUS;
    table->data[363] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[363].data[0].term = T_HASH;
    table->data[360] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[360].data[0].term = T_NOT;
    table->data[78] = (exp_list_t){ .valid = true, .size = 3, .data = alloc_tokens(3) };
    table->data[78].data[0].term = T_LPAREN;
    table->data[78].data[1].is_nterm = true;
    table->data[78].data[1].nterm = NT_EXPRESSION;
    table->data[78].data[2].term = T_RPAREN;
    table->data[79] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[79].data[0].term = T_IDENTIFIER;
    table->data[96] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[96].data[0].term = T_NUMBER;
    table->data[85] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[85].data[0].term = T_INTEGER;
    table->data[86] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[86].data[0].term = T_STRING;
    table->data[75] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[75].data[0].term = T_BOOL;
    table->data[82] = (exp_list_t){ .valid = true, .size = 1, .data = alloc_tokens(1) };
    table->data[82].data[0].term = T_NIL;
    return E_OK;
}
void parser_free()
{
    free(table);
    free(mempool.data);
}
